### ISSUE TITLE
DAS installation not running without GPU

### ISSUE THREAD

**Issue by TamirEliav** [janclemenslab/das#57]
Hi
I installed DAS on my new laptop (win 11, only basic intel GPU).
I followed the installation guide (including installing Visual C++ runtime).
When I try to run das from the command line `das gui`, nothing happens for many minutes, then I get the following output, and then it get stuck (not returning to the command prompt):
```
(base) C:\Users\teliav>conda activate das

(das) C:\Users\teliav>das gui
2022-12-15 15:16:46.467876: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-12-15 15:16:46.468299: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-12-15 15:16:46.479078: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: nb5142
2022-12-15 15:16:46.479364: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: nb5142
```

If I terminate the command `das gui` while it's being stuck (after waiting for some time but before giving the output above), this is what I get:
```
(base) C:\Users\teliav>activate das

(das) C:\Users\teliav>das gui
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\das\lib\tempfile.py", line 255, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\envs\\das\\lib\\site-packages\\librosa\\util\\__pycache__\\tmpnw67dij8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\das\Scripts\das-script.py", line 6, in <module>
    from das.cli import main
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\das\cli.py", line 4, in <module>
    from . import train, predict, train_tune
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\das\train.py", line 12, in <module>
    from . import data, models, utils, predict, io, evaluate, tracking, data_hash, augmentation, postprocessing  #, timeseries
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\das\models.py", line 9, in <module>
    from .kapre.time_frequency import Spectrogram
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\das\kapre\__init__.py", line 6, in <module>
    from . import time_frequency
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\das\kapre\time_frequency.py", line 6, in <module>
    from . import backend, backend_keras
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\das\kapre\backend.py", line 18, in <module>
    import librosa
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\librosa\util\utils.py", line 1879, in <module>
    def __shear_dense(X, *, factor=+1, axis=-1):
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\numba\core\decorators.py", line 212, in wrapper
    disp.enable_caching()
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\numba\core\dispatcher.py", line 863, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\numba\core\caching.py", line 601, in __init__
    self._impl = self._impl_class(py_func)
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\numba\core\caching.py", line 333, in __init__
    locator = cls.from_function(py_func, source_path)
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\numba\core\caching.py", line 180, in from_function
    self.ensure_cache_path()
  File "C:\ProgramData\Anaconda3\envs\das\lib\site-packages\numba\core\caching.py", line 107, in ensure_cache_path
    tempfile.TemporaryFile(dir=path).close()
  File "C:\ProgramData\Anaconda3\envs\das\lib\tempfile.py", line 545, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\ProgramData\Anaconda3\envs\das\lib\tempfile.py", line 255, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
KeyboardInterrupt
^C
(das) C:\Users\teliav>
```

when using `das version` it also takes some time until it gives this output (with this command it does get back to the command prompt):
```
(base) C:\Users\teliav>conda activate das

(das) C:\Users\teliav>das version
2022-12-16 10:42:45.309597: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-12-16 10:42:45.309850: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-12-16 10:42:45.319211: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: nb5142
2022-12-16 10:42:45.319448: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: nb5142
INFO:das.cli:  Windows-10-10.0.22621-SP0
INFO:das.cli:  DAS v0.28.4
INFO:das.cli:     GUI is available.
INFO:das.cli:     xarray-behave v0.33.15
INFO:das.cli:     pyqtgraph v0.12.4
INFO:das.cli:     PySide2 v5.13.2
INFO:das.cli:     Qt v5.12.9
INFO:das.cli:
INFO:das.cli:  tensorflow v2.6.0
INFO:das.cli:  keras v2.6.0
INFO:das.cli:     GPU is not available.
INFO:das.cli:
INFO:das.cli:  python v3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:39:05) [MSC v.1929 64 bit (AMD64)]
INFO:das.cli:  pandas v1.5.2
INFO:das.cli:  numpy v1.23.5
INFO:das.cli:  h5py v3.7.0
INFO:das.cli:  scipy v1.9.3
INFO:das.cli:  scikit-learn v1.2.0
INFO:das.cli:  xarray v2022.12.0

(das) C:\Users\teliav>
```

**Comment by postpop** [comment]
Hi, DAS will fall back to using the CPU on a machine w/o an Nvidia graphics card.  DAS still works - I just tested this on a windows machine w/o a GPU but fail to reproduce the issue. I get the same message and then the GUI window opens and everything works as intended.

The error messages you get when cancelling say sth about "PermissionDenied" - maybe sth specific to your machine or user. Do you get the same error on a different windows PC w/o an Nvidia GPU?

**Comment by TamirEliav** [comment]
good catch! I now run the terminal with admin and it works- thanks!
